# No clear secrets in git. Ciphertext only; the in-cluster sealed-secrets
# controller unseals it into Secret dailych0-secrets (envFrom). Sealed (strict
# scope) against the dev cluster cert for namespace sdk-apps-dev.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dailych0-secrets
  namespace: sdk-apps-dev
spec:
  encryptedData:
    INTERACTIVE_SECRET: AgCrMK+DwfV+xtEbG+vtNLkmfvTpLHCFEkqzyw0TmpPArzw7saIrMvnINVrLcYLZlPoFJf7j+ivwW9kFZitbmMQYIFIeL4LKawjqODgC5VQF6F6LQO6FFvzFeijwYMve8GDhMIf6SCO10KkWTQYFevUBUSSzKhJeM5pqprPc+qR2wQg/NKvtEbGYDvlhuV1QPscC22cNM72a5RfWLfUGRLDefFTRvi6fV1+vJgSb6tyw5sBbJxdDkHj9YVONf7f8aA4bgbvbQuSW7EGQu89bNfSKCj2GMrchtck9Nx/37ASd2N2aPwbecBJyho+CbC127Jm43v/0OyaSt0ybDUQWfh4JvPZcsv6M2rrDtaLHgBVmPNPwFEXpjDyYjJYQeWWr6Q97bmErHVAsjcEjTITLYB6Gwe52Lr1zvvbv75HA0KJWRuD0sd5E7z8R1gZGgiX6xG9ZnfPULC00KaJIbF4+cfwOOtbnHWtnO4oGUnXehgkAcPf6Zu8j/hGTItLT5Gw5qipvQm+4fSyVhapFTxmPe+G7hKCIh07fbfUDk7yy0PdC265KWplOERE+pTfSrBTIHY6tpPZEV4WfK+VSGohCjfbuKDUP/c+p4B5llh2baOLc6VVmoi2Hx/kENprNTUz0lJufQjbAz220FWkUhiPnMjevOiSIAvNeVpG1RzzVwyU7jtgH6SLK0NkeG3uJPgFqDprWGki5Z8lLBWfNlM+IoA/mbKSFlNYXSwPX1JjRVuVSCs6J4g5GGcv/33HeYqcWKlo=
  template:
    metadata:
      name: dailych0-secrets
      namespace: sdk-apps-dev
    type: Opaque
