apiVersion: v1
kind: ConfigMap
metadata:
  name: dailych0-config
  labels:
    app.kubernetes.io/name: dailych0
data:
  INSTANCE_DOMAIN: "api.topia.io"
  INSTANCE_PROTOCOL: "https"
  INTERACTIVE_KEY: "Z0SSoDECHDwgdWtHumJq"
  NODE_ENV: "production"
  PORT: "3000"
